add group chat
owncloud/jsxc.chat pull request #33
Opened 2016-11-15 14:18 UTC by coyoty

add group chat if the documents app creates the id and the password for a document

2016-11-15 15:29 UTC, sualko requested changes
>  if the documents app creates the id and the password for a document

Is there a pending pr? Can you reference it?

2016-11-15 15:29 UTC, sualko commented on js/ojsxc.js
> +   if($("#document-title").attr("data-chatroom-password") && $("#document-title").attr("data-chatroom-password")!="undefined") {
Remove `!="undefined"` or use `typeof`.

2016-11-15 15:29 UTC, sualko commented on js/ojsxc.js
> +         jsxc.gui.window.open(roomId+"@"+conferenceServer);
I think it could be annoying, if a new chat window opens for every document.

2016-11-16 12:48 UTC, coyoty commented on js/ojsxc.js
> +         jsxc.gui.window.open(roomId+"@"+conferenceServer);
this is the pull request: https://github.com/owncloud/documents/pull/665

2017-03-23 15:31 UTC, coyoty commented
no longer using owncloud

2017-03-23 15:31 UTC, closed without merging